#!/usr/bin/env python

import os
import kacl
import chalk

def main():
    filename='CHANGELOG_1_1_0_invalid.md'
    changlog_file = os.path.join(os.path.dirname(
        os.path.realpath(__file__)), 'kacl', 'tests' ,"data", filename)
    changelog = kacl.load(changlog_file)
    validation = changelog.validate()

    for error in validation.errors():
        green = chalk.Chalk('green')
        red = chalk.Chalk('red')

        print(filename + ': ' + f'{error.line_number()}:0: ' + red + 'error: '  + chalk.RESET + error.error_message())
        if error.text():
            print(error.text())
            print(green + '^~~~~~~~~~~~~~~~~~~~' + chalk.RESET + '\n')